//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEF.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        public int EmployeeID { get; set; }
        public int UserID { get; set; }
        public int JobCategoryID { get; set; }
        public string EmployeeName { get; set; }
        public System.DateTime DOB { get; set; }
        public string CNIC { get; set; }
        public string FNIC { get; set; }
        public string FatherName { get; set; }
        public int CountryID { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Photo { get; set; }
        public string Qualification { get; set; }
        public string PermanentAddress { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
    
        public virtual CountryTable CountryTable { get; set; }
        public virtual JobCategoryTable JobCategoryTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
